# Generated by Django 4.2.9 on 2024-04-12 11:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_no', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('extension_name', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('administrator', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=50)),
                ('course_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_description', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('school_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prospectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospectus_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('descriptive_title', models.CharField(max_length=50)),
                ('lecture_unit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('laboratory_unit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('credit_unit', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('home_address', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=None)),
                ('update_on', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=None)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_room', to='gsis.college')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_id', to='gsis.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Prospectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('year_level', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectuse_course_name', to='gsis.course')),
                ('pre_requisit1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq1', to='gsis.subject')),
                ('pre_requisit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq2', to='gsis.subject')),
                ('pre_requisit3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq3', to='gsis.subject')),
                ('pre_requisit4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq4', to='gsis.subject')),
                ('pre_requisit5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prereq5', to='gsis.subject')),
                ('prospectus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prospectus_name', to='gsis.prospectus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectus_subject_name', to='gsis.subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_department_name', to='gsis.department'),
        ),
        migrations.CreateModel(
            name='Class_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_class_schedule', to='gsis.enrollment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_class_schedule', to='gsis.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class_schedule', to='gsis.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=None)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator_user',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsis.user',),
            managers=[
                ('user', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff_user',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsis.user',),
            managers=[
                ('user', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student_user',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsis.user',),
            managers=[
                ('user', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
