# Generated by Django 4.2.9 on 2024-05-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsis', '0002_alter_administrator_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('Summer', 'Summer')], default='1st', max_length=10),
        ),
    ]
